server:
  port: 8888
  servlet:
    context-path: /back
spring:
  datasource:
    url: jdbc:mysql://39.105.108.243:3306/gxx?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  mvc:
    view:
      prefix: /
      suffix: .html

mybatis:
  type-aliases-package: com.gxx.back.bean
  mapper-locations: classpath:/mapping/*.xml

logging:
  level:
    com.gxx.back.dao: trace
